/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Thang Nguyen
 */
public class Main extends JFrame {

   /**
    * Creates new form Main
    */
   public Main() {
      initComponents();
      CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
      cardLayout.show(mainPanel, "Account Card");
      addOptionToList();
   }
   private void addOptionToList() {
      listOption = new ArrayList<>();
      listOption.add(studentOption);
      listOption.add(scheduleOption);
      listOption.add(classOption);
      listOption.add(scoreOption);
      listOption.add(complainOption);
      listOption.add(accountOption);
   }
   private void changeOption(int option) {
      for (int i = 0; i < listOption.size(); i++) {
         JPanel panel = listOption.get(i);
         if (i == option)
            panel.setBackground(new Color(67, 149, 241));
         else
            panel.setBackground(new Color(98, 43, 229));
         listOption.set(i, panel);
      }
      CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
      switch (option) {
         case 0:
            cardLayout.show(mainPanel, "Student Card");
            break;
         case 1:
            cardLayout.show(mainPanel, "Schedule Card");
            break;
         case 2:
            cardLayout.show(mainPanel, "Class Card");
            break;
         case 3:
            cardLayout.show(mainPanel, "Score Card");
            break;
         case 4:
            cardLayout.show(mainPanel, "Complain Card");
            break;
         case 5:
            cardLayout.show(mainPanel, "Account Card");
            break;

      }
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
    * content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        sidePanel = new JPanel();
        studentOption = new JPanel();
        jLabel1 = new JLabel();
        scheduleOption = new JPanel();
        jSeparator7 = new JSeparator();
        jLabel6 = new JLabel();
        classOption = new JPanel();
        jLabel7 = new JLabel();
        jSeparator2 = new JSeparator();
        scoreOption = new JPanel();
        jLabel8 = new JLabel();
        jSeparator3 = new JSeparator();
        complainOption = new JPanel();
        jLabel10 = new JLabel();
        jSeparator5 = new JSeparator();
        accountOption = new JPanel();
        jLabel2 = new JLabel();
        jSeparator6 = new JSeparator();
        mainPanel = new JPanel();
        studentCard = new JPanel();
        btnAddStudentFile = new JButton();
        jLabel3 = new JLabel();
        jTextField1 = new JTextField();
        jLabel4 = new JLabel();
        jTextField2 = new JTextField();
        jLabel5 = new JLabel();
        radioMale = new JRadioButton();
        radioFemale = new JRadioButton();
        jLabel11 = new JLabel();
        jTextField3 = new JTextField();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        boxClassAddStudent = new JComboBox<>();
        jScrollPane1 = new JScrollPane();
        tableListStudent = new JTable();
        btnSaveAddStudent = new JButton();
        scheduleCard = new JPanel();
        jLabel17 = new JLabel();
        jScrollPane2 = new JScrollPane();
        tableSchedule = new JTable();
        boxClassSchedule = new JComboBox<>();
        jLabel20 = new JLabel();
        jLabel21 = new JLabel();
        boxSubjectSchedule = new JComboBox<>();
        btnAddSchedule = new JButton();
        btnDeleteStudentSchedule = new JButton();
        classCard = new JPanel();
        jLabel18 = new JLabel();
        jScrollPane3 = new JScrollPane();
        jTable3 = new JTable();
        boxListClass = new JComboBox<>();
        jLabel14 = new JLabel();
        jLabel15 = new JLabel();
        boxSubjectClass = new JComboBox<>();
        btnDeleteStudent = new JButton();
        scoreCard = new JPanel();
        jLabel19 = new JLabel();
        jScrollPane4 = new JScrollPane();
        tableScore = new JTable();
        boxClassScore = new JComboBox<>();
        jLabel23 = new JLabel();
        labelPass = new JLabel();
        jLabel25 = new JLabel();
        labelFail = new JLabel();
        complainCard = new JPanel();
        jLabel22 = new JLabel();
        jScrollPane5 = new JScrollPane();
        tableComplain = new JTable();
        jLabel9 = new JLabel();
        textFieldStart = new JTextField();
        textFieldEnd = new JTextField();
        jLabel16 = new JLabel();
        btnSaveComplain = new JButton();
        jSeparator1 = new JSeparator();
        jLabel27 = new JLabel();
        textFieldDiemGk = new JTextField();
        jLabel28 = new JLabel();
        textFieldDiemCK = new JTextField();
        jLabel29 = new JLabel();
        textFieldDiemKhac = new JTextField();
        jLabel30 = new JLabel();
        textFieldDiemTong = new JTextField();
        jLabel31 = new JLabel();
        btnUpdateScore = new JButton();
        accountCard = new JPanel();
        jLabel32 = new JLabel();
        jLabel40 = new JLabel();
        jLabel41 = new JLabel();
        textFieldPass = new JTextField();
        textFieldRePass = new JTextField();
        jLabel42 = new JLabel();
        btnSavePass = new JButton();
        btnLogOut = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Manager");
        setAlwaysOnTop(true);
        setBackground(new Color(68, 73, 142));
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setName("mainFrame"); // NOI18N

        sidePanel.setBackground(new Color(16, 61, 114));
        sidePanel.setLayout(new GridLayout(0, 1));

        studentOption.setBackground(new Color(98, 43, 229));
        studentOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentOptionMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Sinh viên");

        GroupLayout studentOptionLayout = new GroupLayout(studentOption);
        studentOption.setLayout(studentOptionLayout);
        studentOptionLayout.setHorizontalGroup(
            studentOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(studentOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(studentOptionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        studentOptionLayout.setVerticalGroup(
            studentOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
            .addGroup(studentOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(studentOptionLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel1.getAccessibleContext().setAccessibleName("studentOption");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        sidePanel.add(studentOption);

        scheduleOption.setBackground(new Color(98, 43, 229));
        scheduleOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scheduleOptionMouseClicked(evt);
            }
        });

        jSeparator7.setForeground(new Color(252, 250, 240));
        jSeparator7.setAlignmentX(0.0F);
        jSeparator7.setAlignmentY(0.0F);
        jSeparator7.setPreferredSize(new Dimension(50, 1));

        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel6.setText("Th?i khóa bi?u");

        GroupLayout scheduleOptionLayout = new GroupLayout(scheduleOption);
        scheduleOption.setLayout(scheduleOptionLayout);
        scheduleOptionLayout.setHorizontalGroup(
            scheduleOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(scheduleOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(scheduleOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(scheduleOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator7, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        scheduleOptionLayout.setVerticalGroup(
            scheduleOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
            .addGroup(scheduleOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(scheduleOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(scheduleOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(scheduleOptionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator7, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        jLabel6.getAccessibleContext().setAccessibleName("scheduleOption");

        sidePanel.add(scheduleOption);

        classOption.setBackground(new Color(98, 43, 229));
        classOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classOptionMouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel7.setText("Danh sách l?p");

        jSeparator2.setForeground(new Color(252, 250, 240));
        jSeparator2.setAlignmentX(0.0F);
        jSeparator2.setAlignmentY(0.0F);
        jSeparator2.setPreferredSize(new Dimension(50, 1));

        GroupLayout classOptionLayout = new GroupLayout(classOption);
        classOption.setLayout(classOptionLayout);
        classOptionLayout.setHorizontalGroup(
            classOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(classOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(classOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        classOptionLayout.setVerticalGroup(
            classOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, classOptionLayout.createSequentialGroup()
                                                                       .addGap(9, 9, 9)
                                                                       .addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
            .addGroup(classOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
        );

        jLabel7.getAccessibleContext().setAccessibleName("listClassOption");

        sidePanel.add(classOption);

        scoreOption.setBackground(new Color(98, 43, 229));
        scoreOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoreOptionMouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel8.setText("B?ng ?i?m");

        jSeparator3.setForeground(new Color(252, 250, 240));
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        jSeparator3.setPreferredSize(new Dimension(50, 1));

        GroupLayout scoreOptionLayout = new GroupLayout(scoreOption);
        scoreOption.setLayout(scoreOptionLayout);
        scoreOptionLayout.setHorizontalGroup(
            scoreOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(scoreOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(scoreOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(scoreOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator3, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        scoreOptionLayout.setVerticalGroup(
            scoreOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
            .addGroup(scoreOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(scoreOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(scoreOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(scoreOptionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator3, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        jLabel8.getAccessibleContext().setAccessibleName("scoreBoardOption");

        sidePanel.add(scoreOption);

        complainOption.setBackground(new Color(98, 43, 229));
        complainOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complainOptionMouseClicked(evt);
            }
        });

        jLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel10.setText("Phúc kh?o");

        jSeparator5.setForeground(new Color(252, 250, 240));
        jSeparator5.setAlignmentX(0.0F);
        jSeparator5.setAlignmentY(0.0F);
        jSeparator5.setPreferredSize(new Dimension(50, 1));

        GroupLayout complainOptionLayout = new GroupLayout(complainOption);
        complainOption.setLayout(complainOptionLayout);
        complainOptionLayout.setHorizontalGroup(
            complainOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(complainOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(complainOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(complainOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator5, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        complainOptionLayout.setVerticalGroup(
            complainOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
            .addGroup(complainOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(complainOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(complainOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(complainOptionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator5, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        jLabel10.getAccessibleContext().setAccessibleName("listComplainOption");

        sidePanel.add(complainOption);

        accountOption.setBackground(new Color(98, 43, 229));
        accountOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountOptionMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Tài kho?n");

        jSeparator6.setForeground(new Color(252, 250, 240));
        jSeparator6.setAlignmentX(0.0F);
        jSeparator6.setAlignmentY(0.0F);
        jSeparator6.setPreferredSize(new Dimension(50, 1));

        GroupLayout accountOptionLayout = new GroupLayout(accountOption);
        accountOption.setLayout(accountOptionLayout);
        accountOptionLayout.setHorizontalGroup(
            accountOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(accountOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(accountOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(accountOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator6, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        accountOptionLayout.setVerticalGroup(
            accountOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
            .addGroup(accountOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(accountOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(accountOptionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(accountOptionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator6, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        jLabel2.getAccessibleContext().setAccessibleName("accountOption");

        sidePanel.add(accountOption);

        mainPanel.setBackground(new Color(219, 237, 255));
        mainPanel.setLayout(new CardLayout());

        studentCard.setBackground(new Color(255, 246, 246));

        btnAddStudentFile.setText("Thêm t? file");
        btnAddStudentFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddStudentFileMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new Color(103, 0, 251));
        jLabel3.setText("MSSV");

        jLabel4.setForeground(new Color(103, 0, 251));
        jLabel4.setText("H? tên");

        jLabel5.setForeground(new Color(103, 0, 251));
        jLabel5.setText("Gi?i tính");

        buttonGroup1.add(radioMale);
        radioMale.setText("Nam");

        buttonGroup1.add(radioFemale);
        radioFemale.setText("N?");

        jLabel11.setFont(new Font("Dialog", 1, 36)); // NOI18N
        jLabel11.setForeground(new Color(101, 19, 252));
        jLabel11.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel11.setText("Thông tin sinh viên");
        jLabel11.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        jLabel12.setForeground(new Color(103, 0, 251));
        jLabel12.setText("CMND");

        jLabel13.setForeground(new Color(103, 0, 251));
        jLabel13.setText("L?p");

        boxClassAddStudent.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tableListStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableListStudent);

        btnSaveAddStudent.setText("L?u l?i");
        btnSaveAddStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveAddStudentMouseClicked(evt);
            }
        });

        GroupLayout studentCardLayout = new GroupLayout(studentCard);
        studentCard.setLayout(studentCardLayout);
        studentCardLayout.setHorizontalGroup(
            studentCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(studentCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(studentCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(studentCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addComponent(btnSaveAddStudent, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, studentCardLayout.createSequentialGroup()
                                                                               .addGap(0, 6, Short.MAX_VALUE)
                                                                               .addGroup(studentCardLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(studentCardLayout.createSequentialGroup()
                                .addComponent(radioMale)
                                .addGap(45, 45, 45)
                                .addComponent(radioFemale)
                                .addGap(65, 65, 65))
                            .addComponent(boxClassAddStudent, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAddStudentFile, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
            .addGroup(studentCardLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        studentCardLayout.setVerticalGroup(
            studentCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(studentCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(studentCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(studentCardLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnAddStudentFile)
                        .addGap(15, 15, 15)
                        .addGroup(studentCardLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(studentCardLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(7, 7, 7)
                        .addGroup(studentCardLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(radioMale)
                            .addComponent(radioFemale))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(studentCardLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(studentCardLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(boxClassAddStudent, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveAddStudent)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(studentCardLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        mainPanel.add(studentCard, "Student Card");

        scheduleCard.setBackground(new Color(255, 246, 246));

        jLabel17.setFont(new Font("Dialog", 1, 36)); // NOI18N
        jLabel17.setForeground(new Color(101, 19, 252));
        jLabel17.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel17.setText("Th?i khóa bi?u");
        jLabel17.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        tableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableSchedule);

        boxClassSchedule.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setForeground(new Color(103, 0, 251));
        jLabel20.setText("L?p");

        jLabel21.setForeground(new Color(103, 0, 251));
        jLabel21.setText("Môn h?c");

        boxSubjectSchedule.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddSchedule.setText("Thêm th?i khóa bi?u");

        btnDeleteStudentSchedule.setText("Xóa sinh viên");

        GroupLayout scheduleCardLayout = new GroupLayout(scheduleCard);
        scheduleCard.setLayout(scheduleCardLayout);
        scheduleCardLayout.setHorizontalGroup(
            scheduleCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, scheduleCardLayout.createSequentialGroup()
                                                                        .addGap(106, 106, 106)
                                                                        .addComponent(jScrollPane2))
            .addGroup(scheduleCardLayout.createSequentialGroup()
                .addGroup(scheduleCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(scheduleCardLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE))
                    .addGroup(scheduleCardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(scheduleCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(boxClassSchedule, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(85, 85, 85)
                        .addGroup(scheduleCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(scheduleCardLayout.createSequentialGroup()
                                .addComponent(boxSubjectSchedule, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddSchedule, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteStudentSchedule, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 148, Short.MAX_VALUE))
        );
        scheduleCardLayout.setVerticalGroup(
            scheduleCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(scheduleCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(19, 19, 19)
                .addGroup(scheduleCardLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(scheduleCardLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(boxClassSchedule, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxSubjectSchedule, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSchedule)
                    .addComponent(btnDeleteStudentSchedule))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 472, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        mainPanel.add(scheduleCard, "Schedule Card");
        scheduleCard.getAccessibleContext().setAccessibleName("");
        scheduleCard.getAccessibleContext().setAccessibleParent(mainPanel);

        jLabel18.setFont(new Font("Dialog", 1, 36)); // NOI18N
        jLabel18.setForeground(new Color(101, 19, 252));
        jLabel18.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel18.setText("Danh sách l?p");
        jLabel18.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        boxListClass.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("L?p");

        jLabel15.setText("Môn h?c");

        boxSubjectClass.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDeleteStudent.setText("Xóa sinh viên");

        GroupLayout classCardLayout = new GroupLayout(classCard);
        classCard.setLayout(classCardLayout);
        classCardLayout.setHorizontalGroup(
            classCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, classCardLayout.createSequentialGroup()
                                                                     .addContainerGap(294, Short.MAX_VALUE)
                                                                     .addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)
                                                                     .addGap(281, 281, 281))
            .addComponent(jScrollPane3, GroupLayout.Alignment.TRAILING)
            .addGroup(classCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(boxListClass, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(classCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(boxSubjectClass, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnDeleteStudent, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        classCardLayout.setVerticalGroup(
            classCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, classCardLayout.createSequentialGroup()
                                                                     .addContainerGap()
                                                                     .addComponent(jLabel18)
                                                                     .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                     .addGroup(classCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, GroupLayout.Alignment.TRAILING))
                                                                     .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                     .addGroup(classCardLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                    .addComponent(boxSubjectClass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxListClass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteStudent))
                                                                     .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                     .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 554, GroupLayout.PREFERRED_SIZE)
                                                                     .addContainerGap())
        );

        mainPanel.add(classCard, "Class Card");

        jLabel19.setFont(new Font("Dialog", 1, 36)); // NOI18N
        jLabel19.setForeground(new Color(101, 19, 252));
        jLabel19.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel19.setText("B?ng ?i?m");
        jLabel19.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        tableScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableScore);

        boxClassScore.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel23.setText("??u");

        labelPass.setFont(new Font("Dialog", 1, 18)); // NOI18N
        labelPass.setForeground(new Color(0, 153, 51));
        labelPass.setText("50%");

        jLabel25.setText("R?t");

        labelFail.setFont(new Font("Dialog", 1, 18)); // NOI18N
        labelFail.setForeground(new Color(153, 0, 0));
        labelFail.setText("50%");

        GroupLayout scoreCardLayout = new GroupLayout(scoreCard);
        scoreCard.setLayout(scoreCardLayout);
        scoreCardLayout.setHorizontalGroup(
            scoreCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, scoreCardLayout.createSequentialGroup()
                                                                     .addContainerGap(294, Short.MAX_VALUE)
                                                                     .addComponent(jLabel19, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)
                                                                     .addGap(281, 281, 281))
            .addComponent(jScrollPane4, GroupLayout.Alignment.TRAILING)
            .addGroup(scoreCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxClassScore, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(scoreCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPass, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(scoreCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFail, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scoreCardLayout.setVerticalGroup(
            scoreCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, scoreCardLayout.createSequentialGroup()
                                                                     .addContainerGap()
                                                                     .addComponent(jLabel19)
                                                                     .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                                                     .addGroup(scoreCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, scoreCardLayout.createSequentialGroup()
                                                                             .addComponent(jLabel23)
                                                                             .addGap(0, 0, 0)
                                                                             .addGroup(scoreCardLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(boxClassScore, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPass, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GroupLayout.Alignment.TRAILING, scoreCardLayout.createSequentialGroup()
                                                                             .addComponent(jLabel25)
                                                                             .addGap(0, 0, 0)
                                                                             .addComponent(labelFail, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)))
                                                                     .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                     .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 554, GroupLayout.PREFERRED_SIZE)
                                                                     .addContainerGap())
        );

        mainPanel.add(scoreCard, "Score Card");

        jLabel22.setFont(new Font("Dialog", 1, 36)); // NOI18N
        jLabel22.setForeground(new Color(101, 19, 252));
        jLabel22.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel22.setText("Phúc kh?o");
        jLabel22.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        tableComplain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableComplain);

        jLabel9.setText("B?t ??u");

        jLabel16.setText("K?t thúc");

        btnSaveComplain.setText("L?u l?ch phúc kh?o");

        jLabel27.setText("?i?m GK");

        jLabel28.setText("?i?m CK");

        jLabel29.setText("?i?m Khác");

        jLabel30.setText("?i?m t?ng");

        jLabel31.setFont(new Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setForeground(new Color(153, 153, 255));
        jLabel31.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel31.setText("C?p nh?t ?i?m");

        btnUpdateScore.setText("L?u l?i");

        GroupLayout complainCardLayout = new GroupLayout(complainCard);
        complainCard.setLayout(complainCardLayout);
        complainCardLayout.setHorizontalGroup(
            complainCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(complainCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(complainCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, complainCardLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(jLabel22, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(281, 281, 281))
                    .addGroup(GroupLayout.Alignment.TRAILING, complainCardLayout.createSequentialGroup()
                                                                                .addGroup(complainCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, GroupLayout.Alignment.TRAILING)
                            .addGroup(complainCardLayout.createSequentialGroup()
                                .addGroup(complainCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldStart, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldEnd, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSaveComplain, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldDiemGk, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldDiemCK, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldDiemKhac, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldDiemTong, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdateScore, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 15, Short.MAX_VALUE)))
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 673, GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap())))
        );
        complainCardLayout.setVerticalGroup(
            complainCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, complainCardLayout.createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .addComponent(jLabel22)
                                                                        .addGroup(complainCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(complainCardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 606, GroupLayout.PREFERRED_SIZE))
                    .addGroup(complainCardLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addComponent(textFieldStart, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(0, 0, 0)
                        .addComponent(textFieldEnd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveComplain)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addGap(0, 0, 0)
                        .addComponent(textFieldDiemGk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addGap(0, 0, 0)
                        .addComponent(textFieldDiemCK, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(0, 0, 0)
                        .addComponent(textFieldDiemKhac, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addGap(0, 0, 0)
                        .addComponent(textFieldDiemTong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateScore)))
                                                                        .addContainerGap(16, Short.MAX_VALUE))
        );

        mainPanel.add(complainCard, "Complain Card");
        complainCard.getAccessibleContext().setAccessibleParent(mainPanel);

        jLabel32.setFont(new Font("Dialog", 1, 36)); // NOI18N
        jLabel32.setForeground(new Color(101, 19, 252));
        jLabel32.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel32.setText("Tài kho?n");
        jLabel32.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        jLabel40.setFont(new Font("Dialog", 0, 14)); // NOI18N
        jLabel40.setForeground(new Color(0, 153, 153));
        jLabel40.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel40.setText("??i m?t kh?u");

        jLabel41.setText("M?t kh?u");

        jLabel42.setText("Xác nh?n m?t kh?u");

        btnSavePass.setText("L?u l?i");

        btnLogOut.setText("??ng xu?t");

        GroupLayout accountCardLayout = new GroupLayout(accountCard);
        accountCard.setLayout(accountCardLayout);
        accountCardLayout.setHorizontalGroup(
            accountCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(accountCardLayout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(jLabel32, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addGroup(accountCardLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(accountCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(accountCardLayout.createSequentialGroup()
                        .addGroup(accountCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel40, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel41, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldPass)
                            .addComponent(textFieldRePass, GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel42))
                        .addGap(206, 206, 206)
                        .addComponent(btnLogOut, GroupLayout.PREFERRED_SIZE, 247, GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSavePass, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountCardLayout.setVerticalGroup(
            accountCardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, accountCardLayout.createSequentialGroup()
                                                                       .addContainerGap()
                                                                       .addComponent(jLabel32)
                                                                       .addGap(92, 92, 92)
                                                                       .addComponent(jLabel40, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                                                                       .addGap(18, 18, 18)
                                                                       .addComponent(jLabel41)
                                                                       .addGap(0, 0, 0)
                                                                       .addGroup(accountCardLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOut))
                                                                       .addGap(18, 18, 18)
                                                                       .addComponent(jLabel42)
                                                                       .addGap(0, 0, 0)
                                                                       .addComponent(textFieldRePass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                       .addGap(18, 18, 18)
                                                                       .addComponent(btnSavePass)
                                                                       .addContainerGap(331, Short.MAX_VALUE))
        );

        mainPanel.add(accountCard, "Account Card");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
            .addComponent(mainPanel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void accountOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountOptionMouseClicked
      changeOption(5);
   }//GEN-LAST:event_accountOptionMouseClicked

   private void studentOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentOptionMouseClicked
      changeOption(0);
   }//GEN-LAST:event_studentOptionMouseClicked

   private void scheduleOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleOptionMouseClicked
      changeOption(1);
   }//GEN-LAST:event_scheduleOptionMouseClicked

   private void scoreOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreOptionMouseClicked
      changeOption(3);
   }//GEN-LAST:event_scoreOptionMouseClicked

   private void classOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classOptionMouseClicked
      changeOption(2);
   }//GEN-LAST:event_classOptionMouseClicked

   private void complainOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complainOptionMouseClicked
      changeOption(4);
   }//GEN-LAST:event_complainOptionMouseClicked

    private void btnAddStudentFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStudentFileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddStudentFileMouseClicked

    private void btnSaveAddStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveAddStudentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveAddStudentMouseClicked

   /**
    * @param args
    *         the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Main.class.getName())
                                 .log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Main.class.getName())
                                 .log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Main.class.getName())
                                 .log(java.util.logging.Level.SEVERE, null, ex);
      } catch (UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Main.class.getName())
                                 .log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Main().setVisible(true);
         }
      });
   }

   private List<JPanel> listOption;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel accountCard;
    private JPanel accountOption;
    private JComboBox<String> boxClassAddStudent;
    private JComboBox<String> boxClassSchedule;
    private JComboBox<String> boxClassScore;
    private JComboBox<String> boxListClass;
    private JComboBox<String> boxSubjectClass;
    private JComboBox<String> boxSubjectSchedule;
    private JButton btnAddSchedule;
    private JButton btnAddStudentFile;
    private JButton btnDeleteStudent;
    private JButton btnDeleteStudentSchedule;
    private JButton btnLogOut;
    private JButton btnSaveAddStudent;
    private JButton btnSaveComplain;
    private JButton btnSavePass;
    private JButton btnUpdateScore;
    private ButtonGroup buttonGroup1;
    private JPanel classCard;
    private JPanel classOption;
    private JPanel complainCard;
    private JPanel complainOption;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel25;
    private JLabel jLabel27;
    private JLabel jLabel28;
    private JLabel jLabel29;
    private JLabel jLabel3;
    private JLabel jLabel30;
    private JLabel jLabel31;
    private JLabel jLabel32;
    private JLabel jLabel4;
    private JLabel jLabel40;
    private JLabel jLabel41;
    private JLabel jLabel42;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane5;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JSeparator jSeparator5;
    private JSeparator jSeparator6;
    private JSeparator jSeparator7;
    private JTable jTable3;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField jTextField3;
    private JLabel labelFail;
    private JLabel labelPass;
    private JPanel mainPanel;
    private JRadioButton radioFemale;
    private JRadioButton radioMale;
    private JPanel scheduleCard;
    private JPanel scheduleOption;
    private JPanel scoreCard;
    private JPanel scoreOption;
    private JPanel sidePanel;
    private JPanel studentCard;
    private JPanel studentOption;
    private JTable tableComplain;
    private JTable tableListStudent;
    private JTable tableSchedule;
    private JTable tableScore;
    private JTextField textFieldDiemCK;
    private JTextField textFieldDiemGk;
    private JTextField textFieldDiemKhac;
    private JTextField textFieldDiemTong;
    private JTextField textFieldEnd;
    private JTextField textFieldPass;
    private JTextField textFieldRePass;
    private JTextField textFieldStart;
    // End of variables declaration//GEN-END:variables
}
