/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Data.DAO.*;
import Data.DAO.Impl.*;
import Data.HibernateUtils;
import Data.entities.*;
import org.hibernate.Session;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Thang Nguyen
 */
public class StudentUI extends javax.swing.JFrame {

   private List<JPanel> listOption;
   private TaiKhoan taiKhoan;
   List<ChiTietMonHoc> chiTietMonHocList;
   SinhVien sinhVien;
   public StudentUI(TaiKhoan taiKhoan) throws HeadlessException {
      this.taiKhoan = taiKhoan;
      Session session = HibernateUtils.getSessionFactory()
                                      .openSession();
      session.getTransaction()
             .begin();
      ChiTietMonHocDAOImpl.setSession(session);
      SinhVienDAOImpl.setSession(session);
      ChiTietMonHocDAO chiTietMonHocDAO = new ChiTietMonHocDAOImpl();
      SinhVienDAO sinhVienDAO = new SinhVienDAOImpl();
      chiTietMonHocList = chiTietMonHocDAO.getByMssv(taiKhoan.getTaiKhoan());
      sinhVien = sinhVienDAO.getByMSSV(taiKhoan.getTaiKhoan());
      session.close();
      initComponents();
      addOptionToList();
      changeOption(0);
   }
   /**
    * Creates new form StudentUI
    */
   public StudentUI() {

      initComponents();
      addOptionToList();
   }
   private void addOptionToList() {
      listOption = new ArrayList<>();
      listOption.add(scoreOption);
      listOption.add(complainOption);
      listOption.add(accountOption);
   }
   private void changeOption(int option) {
      for (int i = 0; i < listOption.size(); i++) {
         JPanel panel = listOption.get(i);
         if (i == option)
            panel.setBackground(new Color(67, 149, 241));
         else
            panel.setBackground(new Color(98, 43, 229));
         listOption.set(i, panel);
      }
      CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
      switch (option) {
         case 0:
            setupScoreCard();
            cardLayout.show(mainPanel, "Score Card");
            break;
         case 1:
            setupComplainCard();
            cardLayout.show(mainPanel, "Complain Card");
            break;
         case 2:
            cardLayout.show(mainPanel, "Account Card");
            break;

      }
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
    * content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        scoreOption = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        complainOption = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        accountOption = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        scoreCard = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableScore = new javax.swing.JTable();
        complainCard = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        textFieldDiemMuon = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        textFieldLiDo = new javax.swing.JTextField();
        btnSaveComplain = new javax.swing.JButton();
        boxCotDiem = new javax.swing.JComboBox<>();
        boxSubject = new javax.swing.JComboBox<>();
        accountCard = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btnSavePass = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(16, 61, 114));
        sidePanel.setLayout(new java.awt.GridLayout(0, 1));

        scoreOption.setBackground(new java.awt.Color(98, 43, 229));
        scoreOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoreOptionMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bảng điểm");

        jSeparator3.setForeground(new java.awt.Color(252, 250, 240));
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 1));

        javax.swing.GroupLayout scoreOptionLayout = new javax.swing.GroupLayout(scoreOption);
        scoreOption.setLayout(scoreOptionLayout);
        scoreOptionLayout.setHorizontalGroup(
            scoreOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(scoreOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(scoreOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(scoreOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        scoreOptionLayout.setVerticalGroup(
            scoreOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
            .addGroup(scoreOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(scoreOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(scoreOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(scoreOptionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        sidePanel.add(scoreOption);

        complainOption.setBackground(new java.awt.Color(98, 43, 229));
        complainOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complainOptionMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Phúc khảo");

        jSeparator5.setForeground(new java.awt.Color(252, 250, 240));
        jSeparator5.setAlignmentX(0.0F);
        jSeparator5.setAlignmentY(0.0F);
        jSeparator5.setPreferredSize(new java.awt.Dimension(50, 1));

        javax.swing.GroupLayout complainOptionLayout = new javax.swing.GroupLayout(complainOption);
        complainOption.setLayout(complainOptionLayout);
        complainOptionLayout.setHorizontalGroup(
            complainOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(complainOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(complainOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(complainOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        complainOptionLayout.setVerticalGroup(
            complainOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
            .addGroup(complainOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(complainOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(complainOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(complainOptionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        sidePanel.add(complainOption);

        accountOption.setBackground(new java.awt.Color(98, 43, 229));
        accountOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountOptionMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tài khoản");

        jSeparator6.setForeground(new java.awt.Color(252, 250, 240));
        jSeparator6.setAlignmentX(0.0F);
        jSeparator6.setAlignmentY(0.0F);
        jSeparator6.setPreferredSize(new java.awt.Dimension(50, 1));

        javax.swing.GroupLayout accountOptionLayout = new javax.swing.GroupLayout(accountOption);
        accountOption.setLayout(accountOptionLayout);
        accountOptionLayout.setHorizontalGroup(
            accountOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(accountOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(accountOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(accountOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        accountOptionLayout.setVerticalGroup(
            accountOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
            .addGroup(accountOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(accountOptionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(accountOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(accountOptionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        sidePanel.add(accountOption);

        mainPanel.setBackground(new java.awt.Color(219, 237, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(101, 19, 252));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Bảng điểm");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tableScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Điểm GK", "Điểm CK", "Điểm khác", "Điểm tổng", "Lớp", "Kết quả"
            }
        ));
        jScrollPane4.setViewportView(tableScore);

        javax.swing.GroupLayout scoreCardLayout = new javax.swing.GroupLayout(scoreCard);
        scoreCard.setLayout(scoreCardLayout);
        scoreCardLayout.setHorizontalGroup(
            scoreCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scoreCardLayout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        scoreCardLayout.setVerticalGroup(
            scoreCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scoreCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(scoreCard, "Score Card");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(101, 19, 252));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Phúc khảo");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel27.setText("Môn");

        jLabel28.setText("Cột điểm");

        jLabel29.setText("Điểm mong muốn");

        jLabel30.setText("Lí do");

        btnSaveComplain.setText("Lưu lại");
        btnSaveComplain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveComplainMouseClicked(evt);
            }
        });

        boxCotDiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giữa kì", "Cuối kì", "Điểm khác", "Điểm tổng" }));

        boxSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Môn học" }));

        javax.swing.GroupLayout complainCardLayout = new javax.swing.GroupLayout(complainCard);
        complainCard.setLayout(complainCardLayout);
        complainCardLayout.setHorizontalGroup(
            complainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(complainCardLayout.createSequentialGroup()
                .addGroup(complainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldDiemMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldLiDo, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(complainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(complainCardLayout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(complainCardLayout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addGroup(complainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSaveComplain, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boxCotDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        complainCardLayout.setVerticalGroup(
            complainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, complainCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(54, 54, 54)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel28)
                .addGap(4, 4, 4)
                .addComponent(boxCotDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(0, 0, 0)
                .addComponent(textFieldDiemMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addGap(0, 0, 0)
                .addComponent(textFieldLiDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveComplain)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        mainPanel.add(complainCard, "Complain Card");

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(101, 19, 252));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Tài khoản");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel40.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 153, 153));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Đổi mật khẩu");

        jLabel41.setText("Mật khẩu");

        jLabel42.setText("Xác nhận mật khẩu");

        btnSavePass.setText("Lưu lại");
        btnSavePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSavePassMouseClicked(evt);
            }
        });

        btnLogOut.setText("Đăng xuất");
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout accountCardLayout = new javax.swing.GroupLayout(accountCard);
        accountCard.setLayout(accountCardLayout);
        accountCardLayout.setHorizontalGroup(
            accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountCardLayout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addGroup(accountCardLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSavePass, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(accountCardLayout.createSequentialGroup()
                        .addGroup(accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(206, 206, 206)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountCardLayout.setVerticalGroup(
            accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(92, 92, 92)
                .addGroup(accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(accountCardLayout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel41)
                        .addGap(0, 0, 0)
                        .addComponent(btnLogOut))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnSavePass)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        mainPanel.add(accountCard, "Account Card");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void scoreOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreOptionMouseClicked
      changeOption(0);
   }//GEN-LAST:event_scoreOptionMouseClicked

   private void complainOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complainOptionMouseClicked
      changeOption(1);
   }//GEN-LAST:event_complainOptionMouseClicked

   private void accountOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountOptionMouseClicked
      changeOption(2);
   }//GEN-LAST:event_accountOptionMouseClicked

   private void btnSavePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavePassMouseClicked
      // TODO add your handling code here:
      String pass1, pass2;
      pass1 = String.valueOf(jPasswordField1.getPassword());
      pass2 = String.valueOf(jPasswordField2.getPassword());
      if (pass1.equals(pass2)) {
         Session session = HibernateUtils.getSessionFactory()
                                         .openSession();
         session.getTransaction()
                .begin();
         TaiKhoanDAOImpl.setSession(session);
         TaiKhoanDAO taiKhoanDAO = new TaiKhoanDAOImpl();
         TaiKhoan taiKhoan = taiKhoanDAO.getByTaiKhoan(this.taiKhoan.getTaiKhoan());
         taiKhoanDAO.updateMatKhau(taiKhoan, pass1);
         session.getTransaction()
                .commit();
         session.close();
         Toast.makeText(this, "Cập nhật mật khẩu thành công", Toast.Style.SUCCESS)
              .display();

      } else
         Toast.makeText(this, "Mật khẩu không trùng khớp", Toast.Style.SUCCESS)
              .display();
   }//GEN-LAST:event_btnSavePassMouseClicked

   private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
      // TODO add your handling code here:
      EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Login().setVisible(true);
         }
      });
      this.dispose();
   }//GEN-LAST:event_btnLogOutMouseClicked

   private void btnSaveComplainMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btnSaveComplainMouseClicked
      // TODO add your handling code here:
      Session session = HibernateUtils.getSessionFactory()
                                      .openSession();
      session.getTransaction()
             .begin();
      PhucKhaoDAOImpl.setSession(session);
      PhucKhaoDAO phucKhaoDAO = new PhucKhaoDAOImpl();
      PhucKhao phucKhao = new PhucKhao();
      String mon = (String) boxSubject.getSelectedItem();
      String[] parts = mon.split("-");
      phucKhao.setMaMon(parts[0]);
      phucKhao.setMssv(taiKhoan.getTaiKhoan());
      phucKhao.setCotDiem((String) boxCotDiem.getSelectedItem());
      phucKhao.setDiemMongMuon(Double.parseDouble(textFieldDiemMuon.getText()));
      phucKhao.setLiDo(textFieldLiDo.getText());
      phucKhaoDAO.insert(phucKhao);
      session.getTransaction()
             .commit();
      session.close();
      textFieldDiemMuon.setText("");
      textFieldLiDo.setText("");
      boxSubject.setSelectedIndex(0);
      boxCotDiem.setSelectedIndex(0);
   }//GEN-LAST:event_btnSaveComplainMouseClicked
   private void setupScoreCard() {
      DefaultTableModel tableModel = (DefaultTableModel) tableScore.getModel();
      tableModel.setRowCount(chiTietMonHocList.size());
      for (int i = 0; i < chiTietMonHocList.size(); i++) {
         ChiTietMonHoc chiTietMonHoc = chiTietMonHocList.get(i);
         tableModel.setValueAt(String.valueOf(i + 1), i, 0);
         tableModel.setValueAt(sinhVien.getMssv(), i, 1);
         tableModel.setValueAt(chiTietMonHoc.getMaLop() + "-" + chiTietMonHoc.getMaMon(), i, 6);
         if (chiTietMonHoc.getDiemTong() != null) {
            tableModel.setValueAt(chiTietMonHoc.getDiemGk(), i, 2);
            tableModel.setValueAt(chiTietMonHoc.getDiemCk(), i, 3);
            tableModel.setValueAt(chiTietMonHoc.getDiemKhac(), i, 4);
            tableModel.setValueAt(chiTietMonHoc.getDiemTong(), i, 5);
         }
      }
   }
   private void setupComplainCard() {
      Session session = HibernateUtils.getSessionFactory()
                                      .openSession();
      session.getTransaction()
             .begin();
      MonHocDAOImpl.setSession(session);
      MonHocDAO monHocDAO = new MonHocDAOImpl();
      List<String> model = new ArrayList<>();
      for (ChiTietMonHoc chiTietMonHoc : chiTietMonHocList) {
         MonHoc monHoc = monHocDAO.getByMaMon(chiTietMonHoc.getMaMon());
         model.add(chiTietMonHoc.getMaMon() + "-" + monHoc.getTenMon());
      }
      boxSubject.setModel(new DefaultComboBoxModel<>(model.toArray(new String[0])));
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountCard;
    private javax.swing.JPanel accountOption;
    private javax.swing.JComboBox<String> boxCotDiem;
    private javax.swing.JComboBox<String> boxSubject;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSaveComplain;
    private javax.swing.JButton btnSavePass;
    private javax.swing.JPanel complainCard;
    private javax.swing.JPanel complainOption;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel scoreCard;
    private javax.swing.JPanel scoreOption;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tableScore;
    private javax.swing.JTextField textFieldDiemMuon;
    private javax.swing.JTextField textFieldLiDo;
    // End of variables declaration//GEN-END:variables
}
