package View;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainUI extends JFrame {
   private JPanel mainPanel;
   private JLabel optionStudent;
   private JLabel optionSchedule;
   private JLabel optionListClass;
   private JLabel optionTranscript;
   private JLabel optionComplain;
   private JLabel optionListComplain;
   private JLabel optionAccount;
   private JTable table1;
   private JButton button1;
   private JButton button2;
   public MainUI() throws HeadlessException {
      $$$setupUI$$$();
      setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      setContentPane(mainPanel);
      setSize(new Dimension(800, 500));
      //      pack();
   }

   /**
    * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
    * code!
    *
    * @noinspection ALL
    */
   private void $$$setupUI$$$() {
      mainPanel = new JPanel();
      mainPanel.setLayout(new BorderLayout(0, 0));
      mainPanel.setPreferredSize(new Dimension(124, 174));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(7, 1, new Insets(0, 0, 0, 0), -1, -1));
      panel1.setBackground(new Color(-12956267));
      mainPanel.add(panel1, BorderLayout.WEST);
      panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 20, 0, 20), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
      optionStudent = new JLabel();
      Font optionStudentFont = UIManager.getFont("Label.font");
      if (optionStudentFont != null)
         optionStudent.setFont(optionStudentFont);
      optionStudent.setForeground(new Color(-1));
      optionStudent.setText("Sinh viên");
      panel1.add(optionStudent, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      optionListComplain = new JLabel();
      Font optionListComplainFont = UIManager.getFont("Label.font");
      if (optionListComplainFont != null)
         optionListComplain.setFont(optionListComplainFont);
      optionListComplain.setForeground(new Color(-1));
      optionListComplain.setText("Danh sách phúc khảo");
      panel1.add(optionListComplain, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      optionComplain = new JLabel();
      Font optionComplainFont = UIManager.getFont("Label.font");
      if (optionComplainFont != null)
         optionComplain.setFont(optionComplainFont);
      optionComplain.setForeground(new Color(-1));
      optionComplain.setText("Lịch phúc khảo");
      panel1.add(optionComplain, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      optionTranscript = new JLabel();
      Font optionTranscriptFont = UIManager.getFont("Label.font");
      if (optionTranscriptFont != null)
         optionTranscript.setFont(optionTranscriptFont);
      optionTranscript.setForeground(new Color(-1));
      optionTranscript.setText("Bảng điểm");
      panel1.add(optionTranscript, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      optionListClass = new JLabel();
      Font optionListClassFont = UIManager.getFont("Label.font");
      if (optionListClassFont != null)
         optionListClass.setFont(optionListClassFont);
      optionListClass.setForeground(new Color(-1));
      optionListClass.setText("Danh sách lớp");
      panel1.add(optionListClass, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      optionAccount = new JLabel();
      Font optionAccountFont = UIManager.getFont("Label.font");
      if (optionAccountFont != null)
         optionAccount.setFont(optionAccountFont);
      optionAccount.setForeground(new Color(-1));
      optionAccount.setText("Tài khoản");
      panel1.add(optionAccount, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      optionSchedule = new JLabel();
      Font optionScheduleFont = UIManager.getFont("Label.font");
      if (optionScheduleFont != null)
         optionSchedule.setFont(optionScheduleFont);
      optionSchedule.setForeground(new Color(-1));
      optionSchedule.setText("Thời khóa biểu");
      optionSchedule.putClientProperty("html.disable", Boolean.FALSE);
      panel1.add(optionSchedule, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JPanel panel2 = new JPanel();
      panel2.setLayout(new CardLayout(0, 0));
      panel2.setBackground(new Color(-4078128));
      mainPanel.add(panel2, BorderLayout.CENTER);
      final JPanel panel3 = new JPanel();
      panel3.setLayout(new BorderLayout(0, 0));
      panel2.add(panel3, "Card2");
      table1 = new JTable();
      panel3.add(table1, BorderLayout.CENTER);
      final JPanel panel4 = new JPanel();
      panel4.setLayout(new BorderLayout(0, 0));
      panel2.add(panel4, "Card1");
      button1 = new JButton();
      button1.setText("Button");
      panel4.add(button1, BorderLayout.CENTER);
      button2 = new JButton();
      button2.setText("Button");
      panel4.add(button2, BorderLayout.EAST);
   }
   /** @noinspection ALL */
   public JComponent $$$getRootComponent$$$() { return mainPanel; }
   private void createUIComponents() {
      // TODO: place custom component creation code here
   }
}
